# Generated by Django 4.2 on 2024-05-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_preferred_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preferred_theme',
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_theme_is_dark',
            field=models.BooleanField(default=False),
        ),
    ]
